
'use client';

import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Copy, Download } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';

type PreviewModalProps = {
  isOpen: boolean;
  onOpenChange: (open: boolean) => void;
};

const markdownContent = `
# Weekly Polymer Insights

## Key Items

### 1. Bio-based diols for high-Tg PET copolymers
- **Source:** Polymer
- **Summary:** Sorbitol-derived diols used as comonomers raise Tg by 12–18 °C while maintaining processability…

### 2. High-barrier BOPET film via nano-clay masterbatch
- **Source:** Lens (Patent)
- **Summary:** Clay loading <3 wt% with compatibilizer improves O2 barrier; extrusion guidelines provided…

---
*Generated by Ester R&D Platform*
`;

export function PreviewModal({ isOpen, onOpenChange }: PreviewModalProps) {
  const { toast } = useToast();

  const handleCopy = () => {
    navigator.clipboard.writeText(markdownContent);
    toast({ title: 'Copied to clipboard' });
  };

  return (
    <Dialog open={isOpen} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-3xl">
        <DialogHeader>
          <DialogTitle>Digest Preview</DialogTitle>
          <DialogDescription>A preview of your generated report.</DialogDescription>
        </DialogHeader>
        <ScrollArea className="h-[60vh] rounded-md border p-4">
          <pre className="text-sm whitespace-pre-wrap">{markdownContent}</pre>
        </ScrollArea>
        <DialogFooter>
          <Button variant="secondary" onClick={handleCopy}>
            <Copy className="mr-2 h-4 w-4" />
            Copy Markdown
          </Button>
          <Button onClick={() => onOpenChange(false)}>
            <Download className="mr-2 h-4 w-4" />
            Download PDF
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
